var str = readline();
console.log(0);
console.log(1);
console.log(2);
console.log(3);
console.log("libm.so");
console.log("libc.so");
console.log("libdl.so");
console.log(0);
console.log(0);
console.log(0);
console.log(0);
console.log(1);
console.log("output2.txt");
console.log("1.txt");